services:
    # Add db service for all environments
    db:
        build:
            context: ./db
            dockerfile: Dockerfile

    # Add redis service for all environments
    redis:
        image: redis:latest
        ports:
            - '6379:6379'
