services:
    # Add stratos-auth service for development environment
    stratos-auth:
        build:
            context: ./StratosAuth
            dockerfile: Dockerfile.dev
        env_file:
            - ./StratosAuth/.env.dev
        environment:
            - STRATOS_AUTH_PORT=${STRATOS_AUTH_PORT}
        volumes:
            - ./StratosAuth:/app
        ports:
            - '${STRATOS_AUTH_PORT}:${STRATOS_AUTH_PORT}'
        networks:
            - backend

    # Add stratos-db service for development environment
    stratos-db:
        build:
            context: ./StratosDb
            dockerfile: Dockerfile.dev
        volumes:
            - ./StratosDb:/app
        ports:
            - '6544:6544'
        networks:
            - backend
        depends_on:
            - db

    # Add pgadmin service for development environment
    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - '5050:80'
        networks:
            - backend
        depends_on:
            - db

volumes:
    stratos-auth:
    stratos-db:
    pgadmin:
