services:
    # Add stratos-auth service for development environment
    stratos-auth:
        build:
            context: ./StratosAuth
            dockerfile: Dockerfile.dev
        env_file:
            - ./StratosAuth/.env.dev
        volumes:
            - ./StratosAuthDev:/app
        ports:
            - '6543:6543'
